---
version: '3.5'
services:
  plex:
    container_name: plex
    image: plexinc/pms-docker
    hostname: plex
    restart: unless-stopped
    ports: 
      - '32400:32400/tcp' # only important one
      - '3005:3005/tcp'
      - '8324:8324/tcp'
      - '32469:32469/tcp'
      - '1900:1900/udp'
      - '32410:32410/udp'
      - '32412:32412/udp'
      - '32413:32413/udp'
      - '32414:32414/udp'
      - '5353:5353/udp'
    environment:
      TZ: Europe/Zurich
      ADVERTISE_IP: <PLEX_IP>
      HOSTNAME: skywalker
      PLEX_CLAIM: <PLEXTOKEN>
      PLEX_UID: '1000'
      PLEX_GID: '1000'
    volumes:
      - './volumes/transcode/:/transcode/'
      - '/storage/data/docker-volumes/plex/config/:/config/'
      - '/tank/data/media/:/data2/'
      - '/storage/backup/plex:/backup'
    networks:
      monitor:

networks:
  monitor:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.60.0/24